---
- name: "Install dependencies..."
  dnf:
    name: "dnf-plugins-core"
    state: "present"
    update_cache: yes
  tags:
    - "hashicorp_repo"

- name: "Add repository..."
  shell: "dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo"
  tags:
    - "hashicorp_repo"

- name: "Install Terraform..."
  dnf:
    name: "terraform"
    state: "present"
    update_cache: yes
  tags:
    - "terraform"
