---
- name: "Install package..."
  apt:
    pkg: "nginx"
    state: "present"
    update_cache: yes
  tags:
    - "nginx"

- name: "Create nginx config..."
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    force: yes
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "nginx"

- name: "Create directory: {{ nginx_site_path }}"
  file:
    path: "{{ nginx_site_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "nginx"

- name: "Create directory: {{ nginx_cert_path }}"
  file:
    path: "{{ nginx_cert_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "nginx"

- name: "Enable service..."
  systemd_service:
    name: "nginx"
    state: "started"
    enabled: yes
  tags:
    - "nginx"
