---
- name: "Install FreeIPA server..."
  dnf:
    name:
      - "freeipa-server"
      - "freeipa-healthcheck"
    update_cache: yes
    state: "present"
  tags:
    - "ipa_server_install"

- name: "Install FreeIPA client..."
  dnf:
    name: "freeipa-client"
    update_cache: yes
    state: "present"
  tags:
    - "ipa_client_install"

- name: "Configure FreeIPA client..."
  shell: |
    ipa-client-install --server="{{ ipa_server }}.{{ ipa_domain }}" \
    --domain="{{ ipa_domain }}" --realm="{{ ipa_domain | upper }}" \
    --principal="{{ ipa_admin }}" --password='{{ ipa_passwd }}' \
    --mkhomedir --force-join --unattended
  tags:
    - "ipa_client_config"

- name: "Remove FreeIPA client..."
  shell: "ipa-client-install --uninstall --unattended"
  tags:
    - "ipa_client_remove"
