---
- name: "Download helm archive..."
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm }}-linux-amd64.tar.gz"
    dest: "{{ helm_file }}"
    mode: "0644"
  tags:
    - "helm"
    - "k3s_tools"

- name: "Extract helm archive..."
  unarchive:
    src: "{{ helm_file }}"
    dest: "/tmp/"
    include: ["linux-amd64/helm"]
    keep_newer: true
    remote_src: true
  tags:
    - "helm"
    - "k3s_tools"

- name: "Copy helm file..."
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/"
    remote_src: true
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "helm"
    - "k3s_tools"

- name: "Remove tmp file..."
  file:
    path: "/tmp/linux-amd64/helm"
    state: "absent"
  tags:
    - "helm"
    - "k3s_tools"
