---
- name: "Download kubescape archive..."
  get_url:
    url: "https://github.com/kubescape/kubescape/releases/download/v{{ kubescape }}/kubescape-ubuntu-latest"
    dest: "{{ kubescape_file }}"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "kubescape"
