---
- name: "Download nova archive..."
  get_url:
    url: "https://github.com/FairwindsOps/nova/releases/download/v{{ nova }}/nova_{{ nova }}_linux_amd64.tar.gz"
    dest: "{{ nova_file }}"
    mode: "0644"
  tags:
    - "nova"
    - "k3s_tools"

- name: "Extract nova archive..."
  unarchive:
    src: "{{ nova_file }}"
    dest: "/usr/local/bin/"
    include: ["nova"]
    keep_newer: true
    remote_src: true
  tags:
    - "nova"
    - "k3s_tools"
