---
- name: "Install dependencies..."
  apt:
    pkg:
      - "apt-transport-https"
      - "ca-certificates"
      - "lsb-release"
      - "curl"
    state: "present"
    update_cache: yes
  tags:
    - "containerd"
    - "docker"

- name: "Add repository key..."
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: "present"
  tags:
    - "containerd"
    - "docker"

- name: "Add repository..."
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_facts['lsb']['codename'] }} stable"
    state: "present"
  tags:
    - "containerd"
    - "docker"

- name: "Install containerd..."
  apt:
    pkg: "containerd.io"
    state: "present"
    update_cache: yes
  tags:
    - "containerd"
    - "docker"

- name: "Install docker..."
  apt:
    pkg:
      - "docker-ce"
      - "docker-ce-cli"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: "present"
    update_cache: yes
  tags:
    - "docker"
