---
- name: "Install dependencies..."
  apt:
    pkg:
      - "ca-certificates"
      - "curl"
    state: "present"
    update_cache: true
  tags:
    - "containerd"
    - "docker"

- name: "Create keyrings directory..."
  file:
    path: "/etc/apt/keyrings"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "containerd"
    - "docker"

- name: "Add repository key..."
  get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "containerd"
    - "docker"

- name: "Add repository..."
  copy:
    dest: "/etc/apt/sources.list.d/docker.sources"
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/debian
      Suites: {{ ansible_distribution_release }}
      Components: stable
      Architectures: {{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}
      Signed-By: /etc/apt/keyrings/docker.asc
    owner: "root"
    group: "root"
    mode: '0644'
    force: true
  tags:
    - "containerd"
    - "docker"

- name: "Install containerd..."
  apt:
    pkg: "containerd.io"
    state: "present"
    update_cache: true
  tags:
    - "containerd"
    - "docker"

- name: "Install docker..."
  apt:
    pkg:
      - "docker-ce"
      - "docker-ce-cli"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: "present"
    update_cache: true
  tags:
    - "docker"
