---
- name: "Install dependencies..."
  dnf:
    name: "dnf-plugins-core"
    update_cache: yes
  tags:
    - "containerd"
    - "docker"

- name: "Add repository..."
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
  tags:
    - "containerd"
    - "docker"

- name: "Install containerd..."
  apt:
    pkg: "containerd.io"
    state: "present"
    update_cache: yes
  tags:
    - "containerd"
    - "docker"

- name: "Install docker..."
  apt:
    pkg:
      - "docker-ce"
      - "docker-ce-cli"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: "present"
    update_cache: yes
  tags:
    - "docker"
