---
- import_tasks: "docker.yml"
  when: "ansible_facts['os_family']|lower == 'debian' or ansible_facts['os_family']|lower == 'ubuntu'"

- import_tasks: "trivy.yml"
- import_tasks: "dockle.yml"
- import_tasks: "earthly.yml"
- import_tasks: "nerdctl.yml"
