---
- name: "Download nerdctl archive..."
  get_url:
    url: "https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz"
    dest: "{{ nerdctl_file }}"
  tags:
    - "nerdctl"

- name: "Extract nerdctl archive..."
  unarchive:
    src: "{{ nerdctl_file }}"
    dest: "/usr/local/bin/"
    include: ["nerdctl"]
    keep_newer: yes
    remote_src: yes
  tags:
    - "nerdctl"
