---
- name: "Download osv-scanner file..."
  get_url:
    url: "https://github.com/google/osv-scanner/releases/download/v{{ osv_version }}/osv-scanner_{{ osv_version }}_linux_amd64"
    dest: "{{ osv_file }}"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "osv-scanner"
    - "docker_tools"
