---
osv_version: "1.3.3"
osv_file: "/usr/local/bin/osv-scanner"

trivy_version: "0.41.0"
trivy_base_name: "/root/trivy_linux_amd64"

dockle_version: "0.4.11"
dockle_base_name: "/root/dockle_linux_amd64"

earthly_version: "0.7.6"
earthly_file: "/usr/local/bin/earthly"
