---
osv_version: "2.0.1"
osv_file: "/usr/local/bin/osv-scanner"

trivy_version: "0.61.0"
trivy_base_name: "/root/trivy_linux_amd64"

dockle_version: "0.4.15"
dockle_base_name: "/root/dockle_linux_amd64"

earthly_version: "0.8.15"
earthly_file: "/usr/local/bin/earthly"

nerdctl_version: "2.0.4"
nerdctl_file: "/root/nerdctl-linux-amd64.tar.gz"
