---
- name: "Install dependencies..."
  apt:
    pkg:
      - "apt-transport-https"
      - "ca-certificates"
      - "lsb-release"
      - "curl"
    state: "present"
    update_cache: yes
  tags:
    - "wazuh_agent"

- name: "Add repository key..."
  apt_key:
    url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    state: "present"
  tags:
    - "wazuh_agent"

- name: "Add repository..."
  apt_repository:
    repo: "deb https://packages.wazuh.com/4.x/apt stable main"
    state: "present"
  tags:
    - "wazuh_agent"

- name: "Install wazuh-agent..."
  apt:
    pkg: "wazuh-agent"
    state: "present"
    update_cache: yes
  tags:
    - "wazuh_agent"

- name: "Disable service..."
  systemd_service:
    name: "wazuh-agent"
    state: "stopped"
    daemon_reload: yes
    enabled: no
  tags:
    - "wazuh_agent"
