---
- name: "Install dependencies..."
  apt:
    pkg:
      - "apt-transport-https"
      - "ca-certificates"
      - "lsb-release"
      - "curl"
    state: "present"
    update_cache: true
  tags:
    - "tor"

- name: "Add repository key..."
  apt_key:
    url: "https://deb.torproject.org/torproject.org/{{ tor_repo_key }}.asc"
    state: "present"
  tags:
    - "tor"

- name: "Add repository..."
  apt_repository:
    repo: "deb https://deb.torproject.org/torproject.org {{ ansible_facts['lsb']['codename'] }} main"
    state: "present"
  tags:
    - "tor"

- name: "Install tor..."
  apt:
    pkg:
      - "tor"
      - "deb.torproject.org-keyring"
    state: "present"
    update_cache: true
  tags:
    - "tor"

- name: "Update config..."
  template:
    src: "torrc.j2"
    dest: "/etc/tor/torrc"
    force: true
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "tor"

- name: "Enable service..."
  systemd_service:
    name: "tor@default"
    state: "restarted"
    enabled: true
  tags:
    - "tor"
