---
- name: "Clone DockerTemplates repo..."
  git:
    repo: "git@github.com:ShadowUser17/DockerTemplates.git"
    dest: "/root/templates"
    version: "master"
    force: yes
    clone: yes
    key_file: "~/.ssh/git_ssh_key"
    accept_hostkey: yes
  tags:
    - "docker_templates"

- name: "Clone repo: {{ repo_url }}"
  git:
    repo: "{{ repo_url }}"
    dest: "/root/{{ repo_dir }}"
    version: "master"
    force: yes
    clone: yes
    key_file: "~/.ssh/git_ssh_key"
    accept_hostkey: yes
    when: "repo_url is defined && repo_dir is defined"
  tags:
    - "clone_repo"
