---
- name: "Clone DockerTemplates repo..."
  git:
    repo: "git@github.com:ShadowUser17/DockerTemplates.git"
    dest: "/root/templates"
    version: "master"
    key_file: "~/.ssh/git_ssh_key"
    force: true
    clone: true
    accept_hostkey: true
  tags:
    - "docker_templates"

- name: "Clone repo: {{ repo_url }}"
  git:
    repo: "{{ repo_url }}"
    dest: "/root/{{ repo_dir }}"
    version: "{{ repo_branch }}"
    key_file: "~/.ssh/git_ssh_key"
    force: true
    clone: true
    accept_hostkey: true
  tags:
    - "clone_repo"
