---
- name: "Download cilium_cli archive..."
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz"
    dest: "{{ cilium_cli_file }}"
    mode: "0644"
  tags:
    - "cilium_cli"
    - "k3s_hubble"
    - "k3s_cilium"

- name: "Extract cilium_cli archive..."
  unarchive:
    src: "{{ cilium_cli_file }}"
    dest: "/usr/local/bin/"
    include: ["cilium"]
    keep_newer: yes
    remote_src: yes
    owner: "root"
    group: "root"
  tags:
    - "cilium_cli"
    - "k3s_hubble"
    - "k3s_cilium"

- name: "Install cilium..."
  shell: |
    cilium install --version "{{ cilium_version }}" \
    --helm-set "prometheus.enabled=true" \
    --helm-set "operator.prometheus.enabled=true"
  tags:
    - "k3s_cilium"

- name: "Validate cilium..."
  shell: "cilium status --wait"
  tags:
    - "k3s_cilium"

- name: "Enable hubble..."
  shell: "cilium hubble enable"
  tags:
    - "k3s_hubble"
