---
- name: "Download flux archive..."
  get_url:
    url: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
    dest: "{{ flux_file }}"
    mode: "0644"
  tags:
    - "flux"

- name: "Extract flux archive..."
  unarchive:
    src: "{{ flux_file }}"
    dest: "/usr/local/bin/"
    include: ["flux"]
    keep_newer: yes
    remote_src: yes
    owner: "root"
    group: "root"
  tags:
    - "flux"

- name: "Install flux..."
  shell: "flux install"
  tags:
    - "flux"

- name: "Add k8s-bootstrap..."
  shell: "kubectl apply -f https://raw.githubusercontent.com/ShadowUser17/k8s-bootstrap/master/flux/k8s-bootstrap.yaml"
  tags:
    - "flux_source"

- name: "Add docker-templates..."
  shell: "kubectl apply -f https://raw.githubusercontent.com/ShadowUser17/k8s-bootstrap/master/flux/docker-templates.yaml"
  tags:
    - "flux_source"
