---
- name: "Download istio archive..."
  get_url:
    url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux-amd64.tar.gz"
    dest: "{{ istio_file }}"
    mode: "0644"
  tags:
    - "istio"

- name: "Extract istio archive..."
  unarchive:
    src: "{{ istio_file }}"
    dest: "/tmp/"
    keep_newer: yes
    remote_src: yes
    owner: "root"
    group: "root"
  tags:
    - "istio"

- name: "Copy istioctl file..."
  copy:
    src: "/tmp/istio-{{ istio_version }}/bin/istioctl"
    dest: "/usr/local/bin/"
    remote_src: true
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "istio"

- name: "Remove tmp file..."
  file:
    path: "/tmp/istio-{{ istio_version }}"
    state: "absent"
  tags:
    - "istio"

- name: "Install istio..."
  shell: "istioctl install --verify -y"
  tags:
    - "istio"
