---
- name: "Download k3s script..."
  get_url:
    url: "https://get.k3s.io"
    dest: "{{ k3s_file }}"
    mode: "0755"
  tags:
    - "k3s_server"
    - "k3s_agent"
    - "k3s_network_none"

- name: "Install k3s server..."
  shell: |
    INSTALL_K3S_CHANNEL="{{ k3s_version }}" {{ k3s_file }} server \
    --token "{{ k3s_token }}" \
    --node-name "server" \
    --with-node-id \
    --disable "traefik"
  tags:
    - "k3s_server"

- name: "Install k3s server without network..."
  shell: |
    INSTALL_K3S_CHANNEL="{{ k3s_version }}" {{ k3s_file }} server \
    --token "{{ k3s_token }}" \
    --node-name "server" \
    --with-node-id \
    --disable "traefik" \
    --flannel-backend "none" \
    --disable-network-policy
  tags:
    - "k3s_network_none"

- name: "Install k3s agent..."
  shell: |
    INSTALL_K3S_CHANNEL="{{ k3s_version }}" {{ k3s_file }} agent \
    --server "{{ k3s_server }}" \
    --token "{{ k3s_token }}" \
    --node-name "agent" \
    --with-node-id
  tags:
    - "k3s_agent"

- name: "Create .kube directory..."
  file:
    path: "/root/.kube"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "k3s_config"

- name: "Configure kubectl..."
  copy:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/root/.kube/config"
    remote_src: true
    owner: "root"
    group: "root"
    mode: "0600"
  tags:
    - "k3s_config"
