---
- import_tasks: "debian.yml"
  when: "ansible_facts['os_family']|lower == 'debian'"

- name: "Download tmux.conf..."
  get_url:
    url: "https://raw.githubusercontent.com/ShadowUser17/BasicInstalls/master/user/tmux.conf"
    dest: "/root/.tmux.conf"
    force: yes
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "configure"
