---
- name: "Update all packages for DEB..."
  apt:
    pkg: "*"
    state: "latest"
    update_cache: yes
  tags:
    - "update-all"

- name: "Install base packages for DEB..."
  apt:
    pkg:
      - "git"
      - "curl"
      - "htop"
      - "ncdu"
      - "unzip"
      - "tcpdump"
      - "bash-completion"
    state: "present"
    update_cache: yes
  tags:
    - "install-base"
