---
- name: "Update all packages for DEB..."
  apt:
    pkg: "*"
    state: "latest"
    update_cache: yes
  tags:
    - "update"

- name: "Install base packages for DEB..."
  apt:
    pkg:
      - "git"
      - "curl"
      - "tmux"
      - "htop"
      - "ncdu"
      - "tree"
      - "links"
      - "unzip"
      - "tcpdump"
      - "bash-completion"
    state: "present"
    update_cache: yes
  tags:
    - "bootstrap"

- name: "Install k3s packages for DEB..."
  apt:
    pkg:
      - "iptables"
      - "open-iscsi"
    state: "present"
    update_cache: yes
  tags:
    - "k3s-deps"

- name: "Install python packages for DEB..."
  apt:
    pkg:
      - "python3-setuptools"
      - "python3-pip"
      - "python3-dev"
      - "python3-venv"
    state: "present"
    update_cache: yes
  tags:
    - "python-env"
