---
- name: "Update all packages for DEB..."
  apt:
    pkg: "*"
    state: "latest"
    update_cache: yes
  tags:
    - "update-all"

- name: "Install base packages for DEB..."
  apt:
    pkg:
      - "git"
      - "curl"
      - "tmux"
      - "htop"
      - "ncdu"
      - "unzip"
      - "tcpdump"
      - "bash-completion"
    state: "present"
    update_cache: yes
  tags:
    - "install-base"

- name: "Install python packages for DEB..."
  apt:
    pkg:
      - "python3-setuptools"
      - "python3-pip"
      - "python3-dev"
      - "python3-venv"
    state: "present"
    update_cache: yes
  tags:
    - "python-env"
