---
- name: "Update all packages for RPM..."
  dnf:
    name: "*"
    state: "latest"
    update_cache: yes
  tags:
    - "update"

- name: "Install base packages for RPM..."
  dnf:
    name:
      - "git"
      - "curl"
      - "tmux"
      - "htop"
      - "ncdu"
      - "unzip"
      - "tcpdump"
      - "bash-completion"
    state: "present"
    update_cache: yes
  tags:
    - "bootstrap"
