---
- name: "Update all packages for RPM..."
  dnf:
    name: "*"
    state: "latest"
    update_cache: yes
  tags:
    - "update"

- name: "Install base packages for RPM..."
  dnf:
    name:
      - "git"
      - "curl"
      - "tmux"
      - "htop"
      - "ncdu"
      - "tree"
      - "links"
      - "unzip"
      - "tcpdump"
      - "bash-completion"
      - "audit"
      - "audit-rules"
    state: "present"
    update_cache: yes
  tags:
    - "bootstrap"

- name: "Install bcc packages for RPM..."
  dnf:
    name:
      - "bcc-tools"
      - "kernel-devel"
      - "kernel-headers"
    state: "present"
    update_cache: yes
  tags:
    - "bcc-tools"
