---
- name: "Create user..."
  user:
    name: "{{ user_name }}"
    shell: "{{ user_shell }}"
    groups: "{{ user_groups }}"
    state: "present"
    create_home: yes
  tags:
    - "add_user"

- name: "Add sudoers rules..."
  template:
    src: "sudo_rules.j2"
    dest: "/etc/sudoers.d/{{ user_name }}"
    force: yes
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "add_sudoers"

# - name: "Add ssh key..."
#   authorized_key:
#     user: "{{ ssh_user }}"
#     key: "{{ lookup('file', ssh_file) }}"
#     state: "present"
#   tags:
#     - "add_ssh_key"
