---
- name: "Create user..."
  user:
    name: "{{ jenkins_user }}"
    home: "{{ jenkins_base_dir }}/{{ jenkins_user }}"
    shell: "/sbin/nologin"
    groups: "docker"
    create_home: true
    system: true
    state: "present"
  tags:
    - "jenkins_install"

- name: "Download war file..."
  get_url:
    url: "https://get.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war"
    dest: "{{ jenkins_base_dir }}/{{ jenkins_user }}/{{ jenkins_file }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: "0644"
  tags:
    - "jenkins_install"
    - "jenkins_update"

- name: "Install dependencies..."
  apt:
    pkg:
      - "fontconfig"
      - "openjdk-21-jre"
    state: "present"
    update_cache: true
  tags:
    - "jenkins_install"

- name: "Create service..."
  template:
    src: "jenkins.service.j2"
    dest: "/etc/systemd_service/system/jenkins.service"
    force: true
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "jenkins_install"

- name: "Enable service..."
  systemd_service:
    name: "jenkins"
    state: "restarted"
    daemon_reload: true
    enabled: true
  tags:
    - "jenkins_install"
    - "jenkins_update"
