---
- hosts: "all"
  name: "Prepare VM"
  become: true
  # debugger: "on_failed"
  roles:
    - "packages"
    - "configs"
    - "users"
    - "repos"
    - "cdktf"
    - "nodejs"
    - "golang"
    - "nerdctl"
    - "aws_tools"
