---
- hosts: "all"
  name: "Prepare VM"
  become: true
  # debugger: "on_failed"
  roles:
    - "packages"
    - "configs"
    - "command"
    - "users"
    - "repos"
    - "nodejs"
    - "golang"
    - "jsonnet"
    - "k3s_tools"
    - "aws_tools"
    - "terraform"
    - "github_tools"
