---
- hosts: "all"
  name: "Configure optional services..."
  become: true
  # debugger: "on_failed"
  roles:
    - "nfs"
    - "k3s"
    - "tor"
    - "nginx"
    - "vector"
    - "docker"
    - "jenkins"
    - "freeipa"
    - "promtail"
    - "tetragon"
    - "syslog_ng"
    - "wazuh_agent"
    - "node_exporter"
    - "github_runner"
