---
- hosts: "all"
  name: "Configure optional services..."
  become: true
  # debugger: "on_failed"
  roles:
    - "nfs"
    - "nginx"
    - "vector"
    - "jenkins"
    - "node_exporter"
    - "github_runner"
